version: '3.8'

services:
  db:
    image: postgres:9.6
    container_name: challenge_postgres_db
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: challenge2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
